title: CAV 2027
author: International Conference on Computer-Aided Verification
url: "https://conferences.i-cav.org"
baseurl: "/2027"

github:
  repository_url: https://github.com/i-cav/2027
  source:
    branch: master

navbar-links:
  Authors:
    - Call for Papers: "/cfp/"
    - Call for Workshops: "/cfw/"
    - Artifact Evaluation: "/artifacts/"
  Program:
    - Overview: "/program/"
    - Keynotes: "/keynote/"
    - Accepted Papers: "/accepted/"
    - Proceedings: "/proceedings/"
    - CAV Award: "/award/"
  Attend:
    - Registration: "/registration/"
    - Hotels: "/hotels/"
    - Venue: "/venue/"
    - Amsterdam: "/amsterdam/"
    - Sponsors: "/sponsors/"
  Organization: "/organization/"

title-on-all-pages: true
edit_page_button: true
remove-ads: true

timezone: "Europe/Amsterdam"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/

kramdown:
  input: GFM

defaults:
  - scope:
      path: ""
    values:
      layout: "page"

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - TODO.md
  - docs/
  - vendor/

plugins:
  - jekyll-sitemap
